// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirbaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7mYtEhiFw494UVjP3j6hLGJIQs4v4IM',
    appId: '1:341643058999:web:c8cde870a8fc421fdf44b2',
    messagingSenderId: '341643058999',
    projectId: 'chatter-box-19d4b',
    authDomain: 'chatter-box-19d4b.firebaseapp.com',
    storageBucket: 'chatter-box-19d4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKW9pjoW4Izqdr-RFyUW9oO40C3xvWrHA',
    appId: '1:341643058999:android:97fa0ad4a2cbd3fcdf44b2',
    messagingSenderId: '341643058999',
    projectId: 'chatter-box-19d4b',
    storageBucket: 'chatter-box-19d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz2aLakkGFF-aB1Wr4_l9jKgWhMSYl08g',
    appId: '1:341643058999:ios:ccceaf6b8663cb85df44b2',
    messagingSenderId: '341643058999',
    projectId: 'chatter-box-19d4b',
    storageBucket: 'chatter-box-19d4b.appspot.com',
    iosBundleId: 'com.example.chatterBox',
  );

}